version: '2'

services:
  user-db:
     image: mysql:5.5
     ports:
      - "3307:3306"
     volumes:
       - user_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: training
       MYSQL_DATABASE: user-service
       MYSQL_USER: docker
       MYSQL_PASSWORD: training
  user-service:
     depends_on:
       - user-db
     image: syndemo/user-service:latest
     ports:
       - "9000:9000"
     restart: always
  product-service:
     depends_on:
       - product-db
     image: syndemo/product-service:latest
     ports:
       - "9001:9001"
     restart: always
  product-db:
     image: mysql:5.5
     ports:
      - "3308:3306"
     volumes:
       - product_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: training
       MYSQL_DATABASE: product-service
       MYSQL_USER: docker
       MYSQL_PASSWORD: training
  review-service:
     depends_on:
       - review-db
     image: syndemo/review-service:latest
     ports:
       - "9002:9002"
     restart: always
  review-db:
     image: mysql:5.5
     ports:
      - "3309:3306"
     volumes:
       - review_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: training
       MYSQL_DATABASE: review-service
       MYSQL_USER: docker
       MYSQL_PASSWORD: training
volumes:
    user_db_data: {}
    product_db_data: {}
    review_db_data: {}
